/**
 * حالات الشاشات المشتركة بين أدوات الفحص: كل حالة اسم وشيفرة تُنفَّذ في الصفحة.
 * يقرؤها zahf (qa-crawl) وفحص الوصول على الهاتف (audit-reach) فلا تفترق القائمتان.
 */
const R=(code)=>code;
module.exports=[
 // ── الترحيب والتعليم ──
 ['welcomeScr',R("Router.reset('welcomeScr')")],
 ['askTut',R("Router.reset('welcomeScr');push('askTut')")],
 ...[0,1,2,3,4].map(i=>[`tutorial-${i}`,R(`Router.reset('welcomeScr');tutStart();T2.i=${i};tDraw()`)]),
 ['tDone',R("Router.reset('welcomeScr');tutStart();tDone()")],
 ['skipAsk',R("Router.reset('welcomeScr');tutStart();push('skipAsk')")],
 // ── العب ──
 ['playScr',R("tab('play')")],
 ['gamesScr',R("tab('play');push('gamesScr')")],
 ['playerCard',R("tab('play');pcOpen('p0123456789ab','نورة',{skin:2,hair:3,hairStyle:1,eyes:0,mouth:2,acc:0,beard:0,bg:1})")],
 ['dmScr',R("tab('play');dmOpen('p0123456789ab','نورة')")],
 ['friendsScr',R("tab('play');push('friendsScr')")],
 ['recScr',R("tab('more');recOpen()")],
 ['chalScr',R("tab('play');push('chalScr')")],
 ['chalList',R("tab('play');CH.list=[{id:'c1',mine:false,done:false,withName:'نورة',qs:['a'],myScore:null,theirScore:2200,at:Date.now(),won:null,seen:false},{id:'c2',mine:true,done:true,withName:'خالد',qs:['a'],myScore:1900,theirScore:1400,at:Date.now(),won:'me',seen:true}];push('chalScr')")],
 ['recCode',R("tab('more');recOpen();setTimeout(()=>{REC.sent=1;REC.mask='s****d@mail.com';recScr()},200)")],
 ['rmInvite',R("tab('play');RM.code='ABCD';RM.game='barra';RM.host=1;RM.solo=0;push('roomScr','barra');setTimeout(()=>{try{rmInvite()}catch(e){}},300)")],
 ['knBot',R("push('rankedScr');knBot(58)")],
 ['playModesScr',R("push('playModesScr')")],
 ['partyScr',R("push('partyScr')")],
 ...['carrom','uno','mafia','draw','barra'].map(g=>[`gameHub-${g}`,R(`push('gameHub','${g}')`)]),
 ...['knowledge','carrom','uno','mafia','drawing','outsider'].map(g=>[`gameRankScr-${g}`,R(`push('gameRankScr','${g}')`)]),
 ['rankGuideScr-placed',R("const p=rankOf('carrom');p.placed=true;p.tier=5;p.div=1;p.rp=40;push('rankGuideScr','carrom')")],
 ['rankGuideScr-unplaced',R("rankOf('knowledge').placed=false;push('rankGuideScr','knowledge')")],
 ['rankedScr-unplaced',R("rankOf('knowledge').placed=false;push('rankedScr')")],
 ['rankedScr-placed',R("const p=rankOf('knowledge');p.placed=true;p.tier=4;p.div=2;p.rp=64;push('rankedScr')")],
 ['evtScr',R("push('evtScr')")],['seasonScr',R("push('seasonScr')")],['misScr',R("push('misScr')")],['achScr',R("push('achScr')")],
 ['storeScr',R("push('storeScr')")],['lbScr',R("push('lbScr')")],['quickScr',R("push('quickScr')")],['netsScr',R("push('netsScr')")],
 ...['general','arab','football','religion','animals','science','geography','puzzles'].map(n=>[`mapScr-${n}`,R(`push('netsScr');push('mapScr','${n}')`)]),
 ['mapScr-unknown',R("push('netsScr');push('mapScr','nope')")],
 ['home',R("Router.reset('home')")],
 // ── المزيد ──
 ['moreScr',R("tab('more')")],['setScr',R("tab('more');push('setScr')")],
 ['setSection-account',R("tab('more');push('setScr');push('setSection','account')")],
 ['setSection-game',R("tab('more');push('setScr');push('setSection','game')")],
 ['setSection-sound',R("tab('more');push('setScr');push('setSection','sound')")],
 ['setSection-all',R("tab('more');push('setScr');const ks=SETS.map(s=>s.k);window.__setKeys=ks;push('setSection',ks[ks.length-1])")],
 ['avScr',R("tab('more');push('avScr')")],['renameAsk',R("tab('more');push('renameAsk')")],['delAsk',R("tab('more');push('delAsk')")],
 ['profScr',R("tab('more');push('profScr')")],['profileView-rival',R("push('profileView',rivalProfile('سالم',{mmrHint:1400}))")],
 // ── البطاقات ──
 ['cardsScr',R("tab('cards')")],
 ...['read','learn','watch','try'].map(t=>[`cardDetail-${t}`,R(`tab('cards');cdTab='${t}';push('cardDetail',+Object.keys(S.cards.owned)[0])`)]),
 ['cardLevels',R("tab('cards');push('cardLevels',+Object.keys(S.cards.owned)[0])")],
 ['levelDetail',R("tab('cards');push('levelDetail',{id:+Object.keys(S.cards.owned)[0],lv:3})")],
 ['deckScr',R("tab('cards');push('deckScr')")],
 ...[0,2,4].map(i=>[`drawLesson-${i}`,R(`tab('cards');_lsn=${i};push('drawLesson')`)]),
 ['tryCard',R("tab('cards');push('tryCard',+Object.keys(S.cards.owned)[0])")],
 // ── المتجر ──
 ['shopScr',R("tab('shop')")],
 ['chestScr-all',R("tab('shop');const ks=Object.keys(ECON.chests);window.__chestKeys=ks;push('chestScr',ks[0])")],
 ['chestScr-2',R("tab('shop');push('chestScr',Object.keys(ECON.chests)[1])")],
 ['chestScr-last',R("tab('shop');const ks=Object.keys(ECON.chests);push('chestScr',ks[ks.length-1])")],
 ['oddsScr',R("tab('shop');push('oddsScr',Object.keys(ECON.chests)[0])")],
 ['rewardScr',R("tab('shop');push('rewardScr',{title:'صندوق المعرفة',list:[{t:'coins',v:120},{t:'frag',id:CARDS[0].id,v:3},{t:'gems',v:5}]})")],
 ['rewardScr-empty',R("tab('shop');push('rewardScr',{title:'مكافآت',list:[]})")],
 ['wildScr',R("tab('shop');push('wildScr')")],['evoShopScr',R("tab('shop');push('evoShopScr')")],
 ...['all','own','locked','fav','deck'].map(t=>[`emoteScr-${t}`,R(`tab('more');emTab='${t}';push('emoteScr')`)]),
 ['colScr',R("tab('more');push('colScr')")],
 // ── النادي ──
 ['clSearchScr-noclan',R("S.clan=null;tab('clubs')")],
 ['clCreateScr',R("S.clan=null;tab('clubs');push('clCreateScr')")],
 ['clubHome',R("qaClan();tab('clubs')")],
 ...['clMembersScr','clInfoScr','clChatScr','clDonorsScr','clSupportScr','clRequestSupportScr','clRequestsScr','clAdminLogScr','clAchScr','clSettingsScr','clEditIdentityScr','clEditJoinScr','clEditPermsScr','clRanksScr','clMyNotifScr','clBannedScr','clTransferScr','clSearchScr','clEventsScr','clMoreScr']
  .map(n=>[n,R(`qaClan();tab('clubs');push('${n}')`)]),
 ['clMemberScr',R("qaClan();tab('clubs');push('clMemberScr',Object.keys(S.clan.mem).find(u=>u!==S.uid))")],
 // ── الغرف والبحث (بلا ناقل: شاشات البديل) ──
 ['mmScr-nocap',R("push('gameHub','uno');push('mmScr',{g:'uno',mode:'casual'})")],
 ['roomScr-nocap',R("push('gameHub','carrom');push('roomScr','carrom')")],
 ['soloScr-carrom',R("push('gameHub','carrom');push('soloScr','carrom')")],
 ['soloScr-uno',R("push('gameHub','uno');push('soloScr','uno')")],
 // ── مباريات الكمبيوتر ──
 ['carrom-2p',R("push('gameHub','carrom');RM.caN=2;soloStart('carrom','mid');await qaWait(500)")],
 ['carrom-shot',R("push('gameHub','carrom');RM.caN=2;soloStart('carrom','mid');await qaWait(400);caPlay({x:200,y:360,vx:-1.5,vy:-6});await qaWait(350)")],
 ['carrom-aim',R("push('gameHub','carrom');RM.caN=2;soloStart('carrom','mid');await qaWait(700);_ca.sx=200;_ca.sxV=200;_ca.drag={sx:200,sy:361.5,px:200,py:380,dx:40,dy:70,cancel:false};caRender()")],
 ['carrom-back',R("push('gameHub','carrom');RM.caN=2;soloStart('carrom','mid');await qaWait(700);_ca.sx=200;_ca.sxV=200;_ca.drag={sx:200,sy:361.5,px:200,py:380,dx:20,dy:-40,cancel:false,back:true};caRender()")],
 ['carrom-cancel',R("push('gameHub','carrom');RM.caN=2;soloStart('carrom','mid');await qaWait(700);_ca.sx=200;_ca.sxV=200;_ca.drag={sx:200,sy:361.5,px:200,py:380,dx:10,dy:-60,cancel:true};caRender()")],
 ['carrom-4p',R("push('gameHub','carrom');RM.caN=4;soloStart('carrom','hard');await qaWait(500)")],
 ['uno-deal',R("push('gameHub','uno');RM.bots=1;soloStart('uno','mid');await qaWait(900)")],
 ['uno-lot',R("push('gameHub','uno');RM.bots=3;soloStart('uno','hard');await qaWait(5400)")],
 ['uno-2p',R("push('gameHub','uno');RM.bots=1;soloStart('uno','mid');await qaWait(600);unoIntroSkip()")],
 ['uno-4p',R("push('gameHub','uno');RM.bots=3;soloStart('uno','hard');await qaWait(600);unoIntroSkip()")],
 ['uno-call',R("push('gameHub','uno');RM.bots=1;soloStart('uno','mid');await qaWait(600);unoIntroSkip();await qaWait(200);RM.uno.call={p:RM.me,said:false};roomDraw()")],
 ['uno-catch',R("push('gameHub','uno');RM.bots=1;soloStart('uno','mid');await qaWait(600);unoIntroSkip();await qaWait(200);RM.uno.call={p:'bot0',said:false};roomDraw()")],
 ['uno-tip',R("push('gameHub','uno');RM.bots=1;soloStart('uno','mid');await qaWait(600);unoIntroSkip();unoHint(0)")],
 ['room-leave-confirm',R("push('gameHub','carrom');RM.caN=2;soloStart('carrom','mid');await qaWait(400);back()")],
 // ── مباراة المعرفة ──
 ['matchIntro',R("push('rankedScr');matchIntro()")],
 ['match-quick',R("push('rankedScr');startRanked()")],
 ...['odd','timeline','belongs','link','story','reveal','map','match','estimate','twostage','bell','chain','auction','duel','reverse'].map(k=>[`match-${k}`,R(`push('rankedScr');startRanked();M.rounds=['${k}','quick'];M.i=0;mRound()`)]),
 ['match-menu',R("push('rankedScr');startRanked();toggleMenu()")],
 ['match-quitAsk',R("push('rankedScr');startRanked();quitMatch()")],
 ['mResult-win',R("push('rankedScr');const res=resolveMatch({gameId:'knowledge',mode:'ranked',matchId:'qa'+Date.now(),result:{won:true},opponents:[{mmr:1000}]});M={log:[{ok:1},{ok:1},{ok:0},{ok:1}],rival:RIVALS[0],me:3,opp:1};Router.enter('mResult',[res,true,120,40,3],{replace:true});mResult(res,true,120,40,3)")],
 ['mResult-loss',R("push('rankedScr');const res=resolveMatch({gameId:'knowledge',mode:'ranked',matchId:'qb'+Date.now(),result:{won:false},opponents:[{mmr:1000}]});M={log:[{ok:0},{ok:1},{ok:0},{ok:0}],rival:RIVALS[1],me:1,opp:3};Router.enter('mResult',[res,false,30,10,0],{replace:true});mResult(res,false,30,10,0)")],
 // ── جولة الأسئلة القديمة ──
 ['quiz-draw',R("push('quickScr');vsScr()")],
 ['quiz-answered',R("push('quickScr');vsScr();ansr('0')")],
 ['quiz-done',R("push('quickScr');vsScr();G.i=G.qs.length-1;G.pts=1200;G.ok=7;done()")],
 ['quiz-exit-confirm',R("push('quickScr');vsScr();back()")],
 // ── ليلة العائلة: برا السالفة ──
 ['barraSetup',R("push('partyScr');ptWay='pass';ptOpen('barra')")],
 ['barra-deal-hidden',R("push('partyScr');ptWay='pass';ptOpen('barra');barraStart()")],
 ['barra-deal-word',R("push('partyScr');ptWay='pass';ptOpen('barra');barraStart();PT.spy=99;PT.shown=true;barraDeal()")],
 ['barra-deal-spy',R("push('partyScr');ptWay='pass';ptOpen('barra');barraStart();PT.spy=0;PT.shown=true;barraDeal()")],
 ['barra-talk',R("push('partyScr');ptWay='pass';ptOpen('barra');barraStart();barraTalk()")],
 ['barra-vote',R("push('partyScr');ptWay='pass';ptOpen('barra');barraStart();barraVote()")],
 ['barra-end',R("push('partyScr');ptWay='pass';ptOpen('barra');barraStart();barraEnd(PT.spy)")],
 ['party-exit-confirm',R("push('partyScr');ptWay='pass';ptOpen('barra');barraStart();back()")],
 // ── مافيا ──
 ['mafiaSetup',R("push('partyScr');ptWay='pass';ptOpen('mafia')")],
 ['mafia-deal-hidden',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart()")],
 ['mafia-deal-role',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart();PT.shown=true;mafiaDeal()")],
 ['mafia-gate',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart();PT.idx=PT.n;mafiaDeal()")],
 ['mafia-pick',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart();mafPick('من تغتالون الليلة؟','mafKill')")],
 ['mafia-check',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart();mafCheck(0)")],
 ['mafia-morning',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart();PT.victim=1;PT.saved=2;mafiaMorning()")],
 ['mafia-lynch',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart();PT.roles=['مواطن','مواطن','مافيا','طبيب','محقق','مواطن'];mafLynch(0)")],
 ['mafia-end',R("push('partyScr');ptWay='pass';ptOpen('mafia');mafiaStart();PT.alive=PT.alive.filter(i=>PT.roles[i]!=='مافيا');mafWinCheck()")],
 // ── مسابقة الرسم ──
 ['drawSetup',R("push('partyScr');ptWay='pass';ptOpen('draw')")],
 ['draw-pass',R("push('partyScr');ptWay='pass';ptOpen('draw');drawStart()")],
 ['draw-board',R("push('partyScr');ptWay='pass';ptOpen('draw');drawStart();drawBoard()")],
 ['draw-vote',R("push('partyScr');ptWay='pass';ptOpen('draw');drawStart();PT.imgs=[qaImg('#E24B4A'),qaImg('#2ECC71'),qaImg('#378ADD')];PT.idx=PT.n;drawVote()")],
 ['draw-end',R("push('partyScr');ptWay='pass';ptOpen('draw');drawStart();PT.imgs=[qaImg('#E24B4A'),qaImg('#2ECC71'),qaImg('#378ADD')];PT.votes=[2,1,0];drawEnd()")],
 // ── ألعاب الجلسة: لو خيروك وصراحة ──
 ['lkSetup',R("push('partyScr');push('lkSetup')")],
 ['lk-ask',R("push('partyScr');push('lkSetup');PT.n=4;lkStart()")],
 ['lk-reveal',R("push('partyScr');push('lkSetup');PT.n=4;lkStart();PT.ans=[0,0,0,1];PT.idx=4;lkReveal()")],
 ['lk-end',R("push('partyScr');push('lkSetup');PT.n=4;lkStart();PT.pts=[3,5,2,5];lkEnd()")],
 ['srSetup',R("push('partyScr');push('srSetup')")],
 ['sr-ask',R("push('partyScr');push('srSetup');PT.n=4;srStart()")],
 ['sr-used',R("push('partyScr');push('srSetup');PT.n=4;srStart();PT.swap[PT.idx]=0;srAsk()")],
 ['sr-end',R("push('partyScr');push('srSetup');PT.n=4;srStart();PT.pts=[6,2,4,0];srEnd()")],
 // ── ضد الكمبيوتر: مافيا وبرا السالفة والرسم ──
 ...['mafia','barra','draw'].map(g=>[`soloScr-${g}`,R(`push('gameHub','${g}');push('soloScr','${g}')`)]),
 ['mf-intro',R("window.__vbFast=1;RM.mbN=6;soloStart('mafia','mid')")],
 ['mf-night',R("window.__vbFast=1;RM.mbN=6;soloStart('mafia','mid');VB.roles[0]='مافيا';VB.roles[1]='مواطن';mfNight()")],
 ['mf-talk',R("window.__vbFast=1;RM.mbN=6;soloStart('mafia','mid');VB.roles=['مواطن','محقق','مافيا','مواطن','طبيب','مواطن'];VB.know[2]=true;mfTalk()")],
 ['mf-vote',R("window.__vbFast=1;RM.mbN=6;soloStart('mafia','mid');VB.roles[0]='مواطن';mfVote()")],
 ['mf-end',R("window.__vbFast=1;RM.mbN=6;soloStart('mafia','mid');VB.roles[0]='مواطن';mfEnd('city')")],
 ['br-round',R("window.__vbFast=1;RM.bbN=5;RM.bbCat='أماكن';soloStart('barra','mid');VB.spy=1;brRound()")],
 ['br-ask',R("window.__vbFast=1;RM.bbN=5;RM.bbCat='مهن';soloStart('barra','mid');VB.spy=2;VB.round=2;brAsk()")],
 ['br-final',R("window.__vbFast=1;RM.bbN=5;RM.bbCat='حيوانات';soloStart('barra','mid');VB.spy=1;VB.cast=[{who:0,t:1},{who:1,t:3},{who:2,t:1},{who:3,t:1},{who:4,t:2}];VB.accused=1;brFinal('caught')")],
 ['db-round',R("soloStart('draw','mid');VB.t0=performance.now()-6000")],
 ['db-end',R("soloStart('draw','mid');VB.res=[{w:'بيت',pts:88},{w:'شمس',pts:61},{w:'قطة',pts:0},{w:'سمكة',pts:74},{w:'قلب',pts:40},{w:'ساعة',pts:92}];VB.total=355;VB.i=6;dbEnd()")],
 // ── أوراق وحوارات ──
 ['paySheet',R("tab('shop');paySheet('season_pass')")],
 ['confirmSheet',R("tab('more');confirmSheet('حذف الحساب','سيُمحى كل شيء.','احذف',()=>{})")],
 ['toast',R("tab('play');toast('حُفظ الاسم')")],
];
